### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by atmonshi** [a7medKhalid/filamentEstraha#1]
- [x] hide "mail owner" there is no Estrahas
- [x] allow to add prices while creating a new Estraha, using a repeater component
- [x] in prices add date validation so wont be before "now"
- [x] add custom page to show all prices, for all Estrahas, and add a date filter 
- [x] add Estrahas count in categories list and filter the table with the count

**Comment by atmonshi** [comment]
https://github.com/a7medKhalid/filamentEstraha/commit/f5e700c56567b6d20acd31e08b3ef7f7045920d3#comments

**Comment by atmonshi** [comment]
better UI when creating new estraha
admin/estrahas/create
prices in one row for ex
---
validation error when editing "The name has already been taken."
-------
`DB error: Column not found: 1054 Unknown column 'prices' in`
when saving after edit
(any changes to db should be done via a new migration)
---------------

if it possible to add a seeder? so I can do more testing

**Comment by a7medKhalid** [comment]
Done

**Comment by atmonshi** [comment]
add some widgets...
maybe count all prices and count all estrahas in estrahasResource

**Comment by atmonshi** [comment]
in the prices report, show active indicator if the price currently been used based on the date

**Comment by atmonshi** [comment]
make the price relationship as tabs, when editing Estraha.
add new page view Estraha

**Comment by atmonshi** [comment]
in prices pages, use grouping by date for the table
